Name:           ros-indigo-kinect-2d-scanner
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS kinect_2d_scanner package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/kinect_2d_scanner
Source0:        %{name}-%{version}.tar.gz

Requires:       mrpt-devel
Requires:       ros-indigo-dynamic-reconfigure
Requires:       ros-indigo-mrpt-bridge
BuildRequires:  mrpt-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-driver-base
BuildRequires:  ros-indigo-dynamic-reconfigure
BuildRequires:  ros-indigo-mrpt-bridge
BuildRequires:  ros-indigo-roscpp

%description
Kinect grabber as 2D laser scans

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Dec 23 2014 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.1.1-0
- Autogenerated by Bloom

